### ISSUE TITLE
courseId is undefined. Sometimes

### ISSUE THREAD

**Issue by sethchilders92** [byuitechops/child-development-kit#1]
Somehow courseId is undefined, which causes many much issues, including crashing the request library that the canvas wrapper uses to basically do everything. Not really sure how to replicate or fix the issue. Both Seth & Sam had this issue on the same day. 

https://github.com/byuitechops/child-development-kit/blob/0d0dc0fd399dbfe625e83b6220dd6f5ce2123d13/postImportSetup.js#L53

**Comment by zachintosh** [comment]
I believe this was fixed with an update to the CDK.
